// //"use server"
// //"use client"
// import React from "react";
// //import { useState, useEffect } from "react";
// //import { fetchCourses } from "@/app/lib/db";
// import Link from "next/link";
// // export const metadata = {
// //     title: "Course Information",
// //     description: "Generated by create next app",
// //   };
// const CourseList = async ({courseData}) =>{
//     //const courseData= await fetchCourses();
    
    

//     return(
//         <div className="courseLists">
//             <div className="infoBox" id="courseListBox">
//                 <table className="table">
//                     <thead>
//                         <tr>
//                             <th>Computing Courses</th>
//                         </tr>
//                     </thead>
//                     <tbody id="computingCoursesData">
                    
//           {courseData.map((item, index) => (
//             <li key={item.id}>
//               <p>
//                 {item.CourseTitle} ...
//                 {/* <a href='#' onClick={(ev) => handleStaffClick(ev, item.id)}>
//                   quick view
//                 </a> */}
//               </p>
//               {/* <p>
//                 <Link href={`staff/${item.id}`}>... More Details</Link>
//               </p> */}
//             </li>
//           ))}
       
                    
            
//                     </tbody>
//                 </table>
//             </div>
//             <div className="infoBox" id="courseListBox">
//                 <table className="table">
//                     <thead>
//                         <tr>
//                             <th>Design Courses</th>
//                         </tr>
//                     </thead>
//                     <tbody id="designCoursesData">
//                     {/* <tr>
//                             <td>{courseData.CourseTitle}</td>
//                         </tr> */}
//                         {/* {courseData.map((item, index) =>(
//                         <tr key={item.id}>
//                             <td>{item.CourseTitle}</td>
//                         </tr>

//                         ))} */}
//                     </tbody>
//                 </table>
//             </div>
        

//         </div>
//     )
// }
// export default CourseList;


//"use server"
"use client"
import React from "react";
import { useState, useEffect } from "react";
//import { fetchCourses } from "@/app/lib/db";
import Link from "next/link";
export const metadata = {
    title: "Course Information",
    description: "Generated by create next app",
  };
const CourseList = async ({coursesList}) =>{
    //const coursesList = await fetchCourses();
    
    let courseType = "computing";
    courseTable(courseType);
    courseType = "design";
    courseTable(courseType);
    function courseTable (courseType){
        useEffect(()=>{
      let elementId = "null";
      //let courseListType = "null";
    // if(courseType == "computing"){ elementId = "computingCoursesData";}
    // else if(courseType == "design"){ elementId = "designCoursesData";}
    fetch(coursesList)
    //.then(response => response.json())
    .then(data => {
        console.dir(data);
        data.forEach((item) => {
            if(item.CourseSubject=='Computing'){elementId = "computingCoursesData";}
            else if(item.CourseSubject=='Art and design'){elementId = "designCoursesData";}
            const courseTable = document.getElementById(elementId);
            const row1 = document.createElement("tr");
            const courseName = document.createElement("td");
            
            const ucasPoints = document.createElement("td");
            const ucasCode = document.createElement("td");
            
            
            const row2 = document.createElement("tr");
            const awardName = document.createElement("td");
            const isUndergraduate = document.createElement("td");
            const isRecruiting = document.createElement("td");
    
            const entryYear = document.createElement("td");
            const studyLength = document.createElement("td");
            const hasFoundation = document.createElement("td");
    
            const row3 = document.createElement("tr");
            const isFullTime = document.createElement("td");
            const courseDescription = document.createElement("td");
            const row4 = document.createElement("tr");
    
            courseName.textContent = item.CourseTitle;
            ucasPoints.textContent = item.UcasPoints;
            ucasCode.textContent = item.UcasCode;
            awardName.textContent = item.CourseAwardName;
            isUndergraduate.textContent = item.CourseType;
            isRecruiting.textContent = item.NoLongerRecruiting;
            if(isRecruiting.textContent == "false") {isRecruiting.textContent = "Recruiting";}
            else if(isRecruiting.textContent == "true") {isRecruiting.textContent = "Not Recruiting";}
            entryYear.textContent = item.YearOfEntry;
            studyLength.textContent = item.StudyLength;
            hasFoundation.textContent = item.HasFoundationYear;
            if(hasFoundation.textContent == "false") {hasFoundation.textContent = "No Foundation Year";}
            else if(hasFoundation.textContent == "true") {hasFoundation.textContent = "Has Foundation Year";}
            isFullTime.textContent = item.ModeOfAttendance;
            courseDescription.textContent = item.CourseSummary;
            row1.appendChild(courseName);
            row1.appendChild(ucasPoints);
            row1.appendChild(ucasCode);
            row2.appendChild(awardName);
            row2.appendChild(isUndergraduate);
            row2.appendChild(isRecruiting);
            row3.appendChild(entryYear);
            row3.appendChild(studyLength);
            row3.appendChild(hasFoundation);
            row4.appendChild(isFullTime);
            row4.appendChild(courseDescription);
            
    
            courseTable.appendChild(row1);
            courseTable.appendChild(row2);
            courseTable.appendChild(row3);
            courseTable.appendChild(row4);
    
    
    
            // row.appendChild(nameCell);
            //     row.appendChild(emailCell);
            //     staffTable.appendChild(row);
    
    
    
    
    
          });
        })
        .catch(error => {
            console.error("Error loading DATA:", error);
        });
      });

};

    return(
        <div className="courseLists">
            <div className="infoBox" id="courseListBox">
                <table className="table">
                    <thead>
                        <tr>
                            <th>Computing Courses</th>
                        </tr>
                    </thead>
                    <tbody id="computingCoursesData">
                        
                    </tbody>
                </table>
            </div>
            <div className="infoBox" id="courseListBox">
                <table className="table">
                    <thead>
                        <tr>
                            <th>Design Courses</th>
                        </tr>
                    </thead>
                    <tbody id="designCoursesData">

                    </tbody>
                </table>
            </div>
        

        </div>
    )
}
export default CourseList;