import Facilities from "./Components/Facilities";
import Footer from "./Components/Footer";
import LearningResources from "./Components/LearningResources";
import ImportantInformation from "./Components/ImportantInformation";
import WorkingWithBusinesses from "./Components/WorkingWithBusinesses";
import Courses from "./Components/Courses";
import CampusMap from "./Components/CampusMap";
import Welcome from './Components/Welcome';
import NavBar from './Components/NavBar';
import Header from './Components/Header';
export const metadata = {
  title: "Cantor College",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <body>
    <header>
<Header></Header>
<NavBar></NavBar>
    </header>
    <main>
<Courses></Courses>
<Facilities></Facilities>
<CampusMap></CampusMap>
<LearningResources></LearningResources>
<ImportantInformation></ImportantInformation>
<WorkingWithBusinesses></WorkingWithBusinesses> 
<Welcome></Welcome>
</main>
<Footer></Footer>
</body>
  );
}